AI Tic Tac Toe Tutorial
ManticoreGamesInc/platform-documentation pull request #583
Opened 2021-05-17 16:31 UTC by nicholasforeman

# Description

Add new AI Tutorial based around Tic Tac Toe.

## Type of change

- [x] New content (non-breaking change which adds functionality)

2021-05-17 18:17 UTC, StanzillaManticore requested changes
One thing that is missing is adding the page to the nav menu. In both `mkdocs.yml` and `mkdocs-prod.yml`

2021-05-17 18:25 UTC, nicholasforeman commented
> One thing that is missing is adding the page to the nav menu. In both `mkdocs.yml` and `mkdocs-prod.yml`

Added (AI Activities). Let me know if you want it under a different name.

2021-05-17 18:31 UTC, StanzillaManticore requested changes, later dismissed
small nits about comments, also apply to the `Final Code` section but I did not add markers there again.

2021-05-17 18:31 UTC, StanzillaManticore commented on src/tutorials/ai_tic_tac_toe.md
> +-- If there is no valid capture position then we need to attempt a capture, otherwise, keep it above Idle priority
I would split to comment to two lines so it does not make the code box scroll on the max width version of the page.

2021-05-17 18:31 UTC, StanzillaManticore commented on src/tutorials/ai_tic_tac_toe.md
> +-- serverUserData contains extra information about the activity that is user-defined and accessible to the server
same as above

2021-05-17 18:31 UTC, StanzillaManticore commented on src/tutorials/ai_tic_tac_toe.md
> +-- If the elapsed time is greater than 2 seconds, activate the trigger and set the capturePosition to be negative
same as above

2021-05-17 18:48 UTC, StanzillaManticore approved these changes
Content review I'll leave to @slinkous

2021-05-18 00:32 UTC, coreslinkous commented
Can we rename to ai_activity_tutorial.md and AI Activity Tutorial in navigation? Otherwise good to go.

2021-05-18 01:16 UTC, merged