Jm terrain reference
ManticoreGamesInc/platform-documentation pull request #659
Opened 2021-07-17 19:48 UTC by MrMiracleMan111

# Description

First draft of the Terrain Reference has been completed.

## Type of change

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New content (non-breaking change which adds functionality)

2021-07-18 14:07 UTC, StanzillaManticore commented
Fixed the tables for you and changed colors/formatting a bit

2021-07-21 18:22 UTC, coreslinkous requested changes
This is really great, and you've amassed even more information than I expected in here that will have a significant impact on creators and spreading hidden Core knowledge. MOst of my feedback is about changing aspects of the tone to better fit a reference (think very dry user manual) and are less like a tutorial. In general :

- Remove any use of "you" and try to swap to talking about the product and what it does
- Remove all the "you will see" which is just tutorialish and redundant
- Remove anything that talks about how important, powerful, useful etc this is. Just focus on what it does, and let the product speak for itself.
- Remove any intro sentences that just say that something is important, and try to redefine the thing multiple times when you write about it. That way if someone doesn't get the first explanation, they can pick it up later.
- Avoid analogies, similes, metaphors, and even comparisons that are just about similarity. They are a very normal part of explanation, usually, but the cognitive reality is that people only tend to understand them if they already understood the thing they are talking about. They also don't translate well, and can frustrate people. Try to just think about what a thing really truly is, and make sure you're specifically conveying that.
- Foliage is a nice example of a very tricky thing to navigate: you have adding a "type" of foliage, and then you have adding the instances of the foliage themselves. Check that section carefully to make sure there's no way that someone would think that they've finished one task when they've actually done a different one. Same with the materials in the

On the whole, great work! This particular variety of technical writing is actually pretty tricky to navigate, because you're trying to get people information quickly, and give it to someone who might only read one tiny sentence or paragraph out of your whole document. Keep that in mind as you make these edits!

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +Terrain is an import aspect of almost all games. Terrain gives games life and immerses players in the world that you have created. Generating terrain is often a difficult task in which teams of artis
- Cut the "Terrain is important" sentence
Reframe to secretly define what terrain actually is. The space players walk/climb move in. The way creators can build a natural ground for game worlds. Something for the uninitiated.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +First click on the ![mountain icon](../img/EditorManual/icons/HierarchyIcon_Terrain.png) icon at the top of your screen.
Add the word for the icon after the image: **Terrain**

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +After you click on the ![mountain icon](../img/EditorManual/icons/HierarchyIcon_Terrain.png) you will see a small dropdown menu called **Terrain Creator**. Click on the **Generate New Terrain** butto
Cut "After you click" and skip straight to "You will see"

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +After clicking on the **Generate New Terrain** button you will see popup window called **GENERATE NEW TERRAIN**. This window contains a multitude of settings that you can use to create your own custo
Generally, we want to avoid these "afters". It turns into you saying every step twice. You could work around it by explaining the effect: Click this button opens this window.

Also, remove "popup"

And "multitude". Focus on what the settings allow you to do rather than the quantity

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +On the left left side of the **GENERATE NEW TERRAIN** window you will see a list of different terrains. In the center of the **GENERATE NEW TERRAIN** window you will see two sections, **General** and
Avoid explaining what they see, and go straight to defining the things that are there. This window contains these sections. 

Also the options are not exactly "terrains", they're predefined height maps that can be used to generate a terrain.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +On the left left side of the **GENERATE NEW TERRAIN** window you will see a list of different terrains. In the center of the **GENERATE NEW TERRAIN** window you will see two sections, **General** and
Also, kudos for CAPS CASE on the menu title.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +The **General** section contains settings that will apply to all types of terrain. The **Voxel Size** setting determines how large the voxels of your terrain will be. A voxel is like a 3D pixel. The
Settings that apply to the generation of all types of terrains. You may not need to explain what a "General" section is, but I could go either way on it.

Move the voxel definition into an !!!info section and take out "like".

Also all of this is really great info.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +
Love the table

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +Now that you have generated your **Terrain** object you may still want to make changes to the shape of your **Terrain**. You can use the **Sculpt** tool to manually change the shape of your terrain.
Cut first sentence.

Click on --> Click
your --> the

This would be a good tone for tutorials, but for a reference, it's less of a walkthrough, and needs to get down to brass tacks quickly. Anywhere you're using "you" should get converted to passive voice.

"X Window hold the features that allow creators to Y" "The Sculpt tool can be accessed through the Properties window when the terrain is selected"

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +Additive sculpting allows you to add the terrain by creating new terrain under your brush. This is useful when you want to manually add terrain features the protrude out of the terrain. This feature
Give the icon a name here. "Additive" or whatever shows when you mouseover it.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +The **View**, **Ground**, and **Up** alignments work differently from the **Surface** alignment because they allow you to create terrain in the air by drawing on an invisible drawing plane.
So glad you got this. So few people know aobut it.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +An important feature of terrain is being able to change the material(s) applied to the terrain. The material system for terrain will allow you to paint up to four different materials on your terrain.
Take out the "an important feature" sentence. Terrains can be painted using Core Materials, or something else that focuses on the function, not the importance.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +The **Paint** tool allows you to manually paint textures onto your terrain. This is extremely useful for creating features like roads and rocky patches. Before you start painting you must select up t
Take out "extremely useful" and rephrase to "this makes it possible" or allows. 

Passive voice instead of "before you start"

Take out the "like a color palette". You could move that into a hint, but in general, we're going to try to stay away for similes and instead have a very specific description. These are the options, or just say palette, but that's still a little metaphor-y.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +To set one of these materials, double click on the checkered sphere image.
set -> select. Because it isn't being applied yet.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +Each of the four materials has its own **Material Side** property that you can set allowing for plenty of variability when designing steep terrain.
I think you should explain this before the workflow of selecting the material channels. Because before understanding it, it's kind of impossible to know what to put where.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +Each of the four materials has its own **Material Side** property that you can set allowing for plenty of variability when designing steep terrain.
Also again, no "you". Focus on what the tool does.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +After you have picked the eight materials (there are four base materials and four side materials) you can click on the ![Icon Close](../img/EditorManual/icons/Icon_Close.png) icon.
Condense to "After you have picked the four base and four side ... "

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +You may have noticed how the materials appear to have depth to them. For example in the video above, the dirt material will sometimes display below the stone material. This is due to the fact that th
Take you "you may have noticed".

I think this needs to be in a different section called "Blending Materials." And I would move the actual explanation that Core Materials have a height map associated with them to more of an !!!info aside, and just focus on the implementation. How frickin' good it looks will be communicated by the image and the creator's own experience.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +You can see the strength of materials by using the **Debug Mode** in the terrain editor. In the **Paint** tab there is setting named **Show Debug Materials**. Click on the box next to **Show Debug Ma
Give this section its own title too. This is very useful stuff.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +An extremely import feature of any terrain is Foliage. In the Core Terrain System, foliage are simple objects that are generated at random positions on a specific terrain material. In most cases, fol
nix "extremely important". Make the sentence define foliage for someone who doesn't know the word, or what it means in the context of game dev, but without them noticing that you're doing it. Something like Terrains can also be [automatically] decorated with 3D objects like grass trees and bushes.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +## Foliage Tool
Just "Foliage"

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +To use foliage, you must first select your **Terrain** object in the hierarchy window. Next, click on the **Foliage** tab in the properties window. This will open the **Foliage** editor for your terr
"you must first select" --> select.

Also cut "this will" and condense to one sentence. Click this to open the Foliage editor.

Cut "your terrain".

Also, this sentence seems to end with a comma.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +To add a new foliage object, click on the **Add Foliage** button. You will now see a pop up window in the center of your screen named **STATIC MESH PICKER**. Select a mesh from this window and then c
Swap the order of the first sentence: Click on the ... to add new foliage. But I would say to add a new 3D object to be used in generating foliage, so that it's clear. 

Also, as usual, cut "you will now see". You can probably just combine those two sentences into one.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +    When adding foliage you can only use assets from the    **STATIC MESH PICKER**. You are not be able to use your own templates as foliage.
Passive voice here.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +You should now see the object you selected as foliage spread randomly throughout your terrain. By default, the foliage you added will be associated with your _first_ material. This means that the fol
First "first" with italics is good, but in the second one redefine "For the material set to Material 1" or something like that.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +To remove foliage, right click on then foliage object. Then select the **Remove** option from the drop down list.
So, there are two different things that people might want to do if they search "removing foliage". It might be how to no longer generate with that static mesh, but most often, what they want to do is erase it from certain areas. We should have both explained here.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +The **Distance Between Instances** property controls how densely one type of foliage is placed. The higher the **Distance Between Instances** the more space there will be between instances of that fo
This is a beautiful example of the kind of passive voice we're looking for in the rest.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +## Heightmaps
This should go up with the Terrain generation section. You can reference there that Weightmaps are explained later, and link to the section, and link back up to heightmaps in Weightmaps.

2021-07-21 18:22 UTC, coreslinkous commented on src/tutorials/terrain_reference.md
> +- 1024 x 1024
Need a Learn More section. You can copy it from another section, but repeat any links you used earlier to things on docs. The Environment Art tutorial would be one, Materials ref. Anything that you might have gotten here but it didn't

2021-07-30 00:48 UTC, StanzillaManticore approved these changes
Just missing the last few comments from Sarah but otherwise lgtm.

2021-07-30 16:44 UTC, merged