Add Boss Tutorial Outline Draft
ManticoreGamesInc/platform-documentation pull request #724
Opened 2021-09-08 11:22 UTC by PopThosePringles

Doing things a little different compared to the race timer tutorial. This time, I have pushed the structure of it now so it can be reviewed first before I write all of the sections.

2021-09-15 10:54 UTC, PopThosePringles commented
Don't worry about reviewing this now. It's changed a bit as I've been working on the tutorial. It's mostly the same, just tweaked a little, ordering changed etc.

2021-09-23 16:32 UTC, coreslinkous requested changes

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +    Place the **PlayerServer** script inside the group **Boss Fight Map** in the **Hierarchy**
Make these subsets part of the larger numbered list. The "you can" sounds like it's optional, and really all of this is necessary to do in order.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +2. Set the **Max Hit Points** to 1000.
Mention that this is in the **Properties** menu the first time.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +In this section you will be create the AI for the boss. The boss needs to transition between different states depending on what is happening in the game. You will use an **AI Activity Handler** that
Link to AI Activity System ref

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +2. Drag **Boss Geo** onto the **BossAIServer** script as a custom property.
Swap "drag" to "add" to avoid ambiguity with adding it as a child.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +1. Create activities table.
Convert to ol to h4 if nesting code blocks between steps

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +1. Add `shoot` table to `activities` table.
Same as above.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +The boss will be shooting a projectile at the current target. Players who get hit by the projectile will take damage.
Optional, but a static image here of what this next phase achieves could help creators understand and remember the distinct phases of the tutorial.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +1. Add **Shoot From** object as a custom property.
h4

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +1. Add `GetDamageable` function.
In general I would use "make" or "create" for any function that they're typing themselves, and "add" for things where they are using previously created parts.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +4. Add the following code.
More specific than code. It's fine to repeat what it is both in this title and in the explanation after.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +1. Add `GetValidTarget` function.
Maybe "write".

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +When a player shoots the boss, it will display **Immune**.
specify where + picture?

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +## Add Player Sprint Ability
At the h2, go back to known or gerund. "Adding Player Sprint ... ", "Giving Your Players The Ability to Sprint".

It needs to sound more general than the h3 to help it break up the sections semantically.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +- Sound turns off.
I really love these ul's. It feels like a checklist.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +1. Add **BossName** custom property.
Might be worth reinforcing custom properties with a picture of each state to check against.

2021-09-23 16:32 UTC, coreslinkous commented on src/tutorials/boss_tutorial.md
> +<https://discord.gg/core-creators>
Take out Discord

2021-09-24 21:09 UTC, merged