Add Perks Tutorial
ManticoreGamesInc/platform-documentation pull request #794
Opened 2021-10-25 15:34 UTC by CommanderFoo

First draft of the perks tutorial.

2021-10-27 17:59 UTC, coreslinkous requested changes

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +In this tutorial you are going to create different perk systems that could be used in your game to make money.
to make money -> to monetize your game.

Paraphrase "perk systems" to say more explicitly what they are. Sellable in-game items and experiences?

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +For further information about the **Perks Program**, click [here](/references/perks/program.md).
Link text should be the name of the document it directs to - Perks Program reference

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Storage will need to be enabled so that data can persist for the player between game sessions. For example, if a player purchases a resource perk, then this will need to be saved for the player so th
Storage > Player Storage

Link to Persistent Storage ref

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +#### Create Pumpkins Perk
This formatting makes my heart gleeful

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +!!! warning "Perk names must be unique. If the **Create Perk** is disabled, check for an existing perk with the same name."
**Create Perk** button

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +- Expand the group and set the **text** property for the **Amount** object in the **Properties Panel**.
This is a Custom Properties group, right? Might not need expanding, and I would just say that that it is in the group. Or is it the Items group?

Also, probably not "panel". Is this a Hierarchy object?

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +The perk reference in the **Properties** panel can be set a few different ways.
ways:

Give this section an h4 header to separate it as information and not three separate actions to take, the way the list above works. Also wouldn't hurt to have it come up in a search.

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +- Drag the template **Perks Tutorial - Resource Shop Item** into the **Items** panel.
numbered not bullets for this list

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +The width of the item, and a little spacing between each item is 165. Move each item after the first item by 165 for the **X Offset** property. You can use the **X Offset** field to handle the calcul
Probably should specify that item is an UI image for the item. 

Like the callout of using operators in properties

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Create the above variables so you have references to the properties you added.
Move these explanations above, and say what information the variables hold.

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Create the `CloseUI` function. This function will be called when the `clickedEvent` listener for `SHOP_BUTTON` is fired, and when the player leaves the `SHOP_TRIGGER` volume.
Move above code

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Test the game and make sure the following work.
. -> :

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Create the variables above so you have reference to each property.
Same as the other times. Summarize what the variables are for and move to before the code. 

Also change title to be more specific about the purpose of the variables

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +| `perk` | Reference to the perk custom property. |
maybe specify that it's a NetRef

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Add the above code to the end of the script. This code will loop over all the local player's resources, and update the resource in the UI. The reason for this, is that when the resources get set on t
Move above (everywhere) and cut the first sentence

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +## Create Tip Jar
Create -> Creating

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Open up the **TipJarClient** script.
cut "up"

2021-10-27 17:59 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +[Perks Program](../references/perks/program.md) | [UI Perk Purchase Button](../api/uiperkpurchasebutton.md)
Anything else you referenced (Storage)

2021-10-28 18:05 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +In this tutorial you are going to create different Sellable in-game items and experiences that could be used in your game to monetize your game.
lowercase sellable

2021-10-28 18:07 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +    A shortcut for the above code can be wrote as `playerData[perkData.storageKey] = playerData[perkData.storageKey] or 0`. If the value is nil, then 0 will be stored. This reduces readability, but i
can be written

2021-10-28 18:09 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Set the **Label** property for the **Tip Jar Trigger** to `Give Tip` in the **Properties** panel.
**Interaction Label**

2021-10-28 18:17 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +This function will be called when the player's resource gets updated. It will check to see if the resource is either of the VIP statuses, and if the value if the status is `1`, then the highest statu
calling

2021-10-28 18:19 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +This function is responsible for checking which perk the player has purchased, awarding the resources, and updating the player's storage.
If time allows, name the function anywhere that says "This function". E.G. The `PerkChanged` script will be responsible for ...

2021-10-28 18:21 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Connect up the events at the end of the script.
With all of these connect steps add that this is so that X function will be called when Y event happens. A little redundant, but you have room.

2021-10-28 18:23 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +    If you have a lot of perks, a better way instead of a large table, is to create a look list in the **Hierarchy**. The list would contain an entry for each perk, along with the data (similar to ea
create a *lookup list

"a better way instead of a large table" -> instead of creating a large table, you could create ... 

Add "This will allow you to edit and update the list from the editor without needing to open the script.

2021-10-28 18:25 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +The resources that the player purchases needs to be stored persistently so that the next session, the game will load from storage the amount of resources the player has.
*need 
*in the next session

2021-10-28 18:25 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +You will need to make some changes to a few of the functions in the **ResourceShopServer** script.
add why

2021-10-28 18:31 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +!!! warning "Multiple perkChanged Events"
Good warning

2021-10-28 18:32 UTC, CommanderFoo commented on src/tutorials/perks_tutorial.md
> +!!! warning "Multiple perkChanged Events"
Thanks :D

2021-10-28 18:33 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Fetches the global list for the **Top Tippers** leaderboard that you created.
Needs a subject, or change it to a command: "Fetch the global list ..."

2021-10-28 18:35 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +
Intro sentence saying that it's already part of the starter project

2021-10-28 18:41 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +- Sprint boost is applied to when purchasing the perk.
cut "to"

2021-10-28 18:45 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +- Trigger interaction label is enabled when entering the trigger volume.
enabled/disabled should be visible/not visible, right? We're not changing intractability.

2021-10-28 18:46 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +Create a new script called `VIPShopServer`, and place it into the **Server** group, in the **Scripts** group. The **VIPShopServer** script will be responsible for setting the player to VIP, and givin
no comma after "coins"

2021-10-28 18:47 UTC, coreslinkous commented on src/tutorials/perks_tutorial.md
> +For feedback and questions, please reach out to us on this tutorial's [forum thread]().
Love this, but change to "join the discussion on this tutorial's [forum thread]()"

2021-10-28 18:48 UTC, coreslinkous requested changes
Just a couple typos

2021-10-28 19:03 UTC, CommanderFoo commented
Think I got them all. Thanks :D

2021-10-28 19:15 UTC, StanzillaManticore approved these changes

2021-10-28 19:15 UTC, merged