Add Concurrent Storage Reference
ManticoreGamesInc/platform-documentation pull request #834
Opened 2021-11-17 13:36 UTC by PopThosePringles

First draft of the reference.

2021-11-18 17:43 UTC, DoubleA-MG requested changes

2021-11-18 17:43 UTC, DoubleA-MG commented on src/references/concurrent_storage.md
> +**Concurrent Storage** allows creators to wite data to a table for players or games concurrently. Meaning the games will have the ability to write data when the player is offline (or online but on a
**Concurrent Storage** allows creators to write* data

2021-11-18 17:43 UTC, DoubleA-MG commented on src/references/concurrent_storage.md
> +There is no request limit For reads, but if they are requested a lot they will end up cached and might be few seconds out of date.
There is no request limit for* reads

2021-11-18 18:02 UTC, DoubleA-MG approved these changes

2021-11-23 16:17 UTC, coreslinkous approved these changes

2021-11-23 16:23 UTC, CommanderFoo commented
Got some additional info I need to add to this reference which I will do tomorrow morning.

- I need to go over the info from Tung and make sure I didn't miss anything.
- Need to add an info box about testing.

2021-11-23 22:02 UTC, DoubleA-MG commented on src/references/concurrent_storage.md
> +- Persistent world
missing period

2021-11-23 22:02 UTC, DoubleA-MG commented on src/references/concurrent_storage.md
> +- Offline / Cross Server Player 2 Player farm help and visit.
Assuming  Player to Player and Player 2 Player are the same, id choose to use one of them for clarity

2021-11-23 22:02 UTC, DoubleA-MG commented on src/references/concurrent_storage.md
> +- Global shared currency, items etc.
Global shared currency, items, etc.

missing comma

2021-11-23 22:13 UTC, DoubleA-MG commented on src/references/concurrent_storage.md
> +- Offline / Cross Server Player 2 Player farm help and visit.
You copy and pasted the example features so line 87 still needs to be fixed, similar to line 98

2021-11-23 22:44 UTC, DoubleA-MG approved these changes

2021-11-24 00:22 UTC, merged