Add Spawn Shared Asset Tutorial
ManticoreGamesInc/platform-documentation pull request #862
Opened 2021-12-08 20:10 UTC by PopThosePringles

2021-12-09 05:51 UTC, DoubleA-MG requested changes
Love the Squid Game idea!

2021-12-09 05:51 UTC, DoubleA-MG commented on src/tutorials/spawn_shared_asset_tutorial.md
> +Create a new script called `EffectManagerClient` and place it into the **Client** folder. This script handle playing audio and effects by listening for broadcasts.
handles* typo

2021-12-09 15:02 UTC, StanzillaManticore commented
lgtm, the only thing that I'm not quite sure about is the name. Would calling it SpawnSharedAsset (no spaces) make more sense since the API is called that? Or if we want to call about the practice of spawning, "Spawning SharedAssets"?

2021-12-09 15:02 UTC, DoubleA-MG approved these changes

2021-12-09 15:08 UTC, PopThosePringles commented
Yeah, I wasn't sure on the name, I think changing it to what you suggest is better than what it is currently. I think macthing the API name is a good choice.

2021-12-09 15:29 UTC, StanzillaManticore commented
To the @slinkous mobile!

2021-12-13 21:19 UTC, StanzillaManticore commented
Going to keep the name like that for now

2021-12-13 21:19 UTC, merged