Add Obby Tutorial
ManticoreGamesInc/platform-documentation pull request #902
Opened 2022-01-18 23:06 UTC by DoubleA-MG

2022-01-18 23:13 UTC, StanzillaManticore commented
slight problem with some of the images, some are caps `.PNG` but you have them as `.png` in the code, that will break on Linux

2022-01-19 12:35 UTC, PopThosePringles requested changes
Good job with the tutorial. I like the pet feature. Nice and simple, but effective.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +Currently, the **Moving Platform** is in a [Default Context](../references/networking.md). This context is useful for objects such as the **Starting Platform** because players need to collide with th
"needs to be in the Default Context (Networked) Context" -> "needs to be a Networked object in the Default Context".

Reads a little better I think.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +!!! warning "**Networked Objects** are the most expensive type of objects because the server has to constantly track and share information about them."
Maybe a little rewording here: "has to constantly track and share information about them." -> "has to send all the information about an object to each player."

Doesn't need to be included, but it's worth knowing that even if 1 property changes, everything about that object (i.e., all the transform data) is sent to clients.

"player" could be switched to "client" if you have defined what a "client" is. Am considering this from a beginners point of view, so "player" might be fine if "client" hasn't been defined.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +Create a new script by pressing the **Script** button ![Script](../img/EditorManual/icons/AssetType_Script.png){: .image-inline-text .image-background } above the scene. Name it `MovingPlatform`. In
I think it's a good idea to get into the habit (especially for beginner tutorials) to specify "Client" and "Server" at the end of a script. This makes it clearer when looking at the Hierarchy, and Project Content.

"MovingPlatform" -> "MovingPlatformServer"

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +Create a new script by pressing the **Script** button ![Script](../img/EditorManual/icons/AssetType_Script.png){: .image-inline-text .image-background } above the scene. Name it `MovingPlatform`. In
"in the **My Scripts** section" -> "in the **My Scripts** folder"

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +    while true do
Considering your loop is infinite, I would use a `Tick` function instead. Move the body of the `while` loop into a function that is called from within the `Tick` function.

If you have no other code that will go into the Tick function, then the no function is needed, throw the code directly into it.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +The **Rotating Platform** needs collision and will also be rotating so it needs to be networked to update for all players properly. Right click the **Rotating Platform** and select **Enable Networkin
Remove "properly".

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +!!! tip "Use the ++Shift+=++ shortcut to spawn the player in Preview Mode where the creator camera currently is in the scene."
"++Shift+=++" -> "++shift+equal++"

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +!!! tip "Use the ++Shift+=++ shortcut to spawn the player in Preview Mode where the creator camera currently is in the scene."
"creator camera" -> "scene camera"

or "viewport camera", "main viewport camera".

It can be called a few different things, would be nice to settle on one. Something to discuss when we get to working on the list.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +The **Shrink Platform** needs collision and will also be changing in size so it needs to be networked to update for all players properly. Right click the **Shrink Platform** and select **Enable Netwo
Remove "properly".

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +    A useful tip to get the **Trigger** in the correct position and size is to copy it from the **Shrink Platform**. There is a **Copy Properties** ![Copy](../img/Obby/copy_icon.png){: .image-inline-
"button that let's the creator" -> "button that lets the creator"

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +    for _, trigger in pairs(triggers) do
```suggestion
    for _, trigger in ipairs(triggers) do
```

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +??? "The Blades_Server" Script
```suggestion
??? "The Blades_Server Script"
```

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +function OnBeginOverlap(whichTrigger, other)
Make function local.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +    function OnBeginOverlap(whichTrigger, other)
Make function local.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +function OnBeginOverlap(whichTrigger, other)
Make function local.

2022-01-19 12:35 UTC, CommanderFoo commented on src/tutorials/obby_tutorial.md
> +    function OnBeginOverlap(whichTrigger, other)
Make function local.

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +function OnInteracted(whichTrigger, other)
Make function local.

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +    function OnInteracted(whichTrigger, other)
Make function local.

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +function OnPlayerLeft(player)
Make function local.

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +    function OnPlayerLeft(player)
Make function local.

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +for _, trigger in pairs(triggers) do
ipairs

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +    for _, pet in pairs(pets) do
ipairs

Your `pets` table is index -> value.

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +	for _, pet in pairs(pets) do
ipairs

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +        for _, pet in pairs(pets) do
ipairs

2022-01-19 12:35 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +        for _, pet in pairs(pets) do
ipairs

2022-01-19 17:52 UTC, DoubleA-MG commented on src/tutorials/obby_tutorial.md
> +Create a new script by pressing the **Script** button ![Script](../img/EditorManual/icons/AssetType_Script.png){: .image-inline-text .image-background } above the scene. Name it `MovingPlatform`. In
hmm. good point. The script was in default context so should I use "Deafult" or "Server" at the end?

2022-01-19 17:56 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +Create a new script by pressing the **Script** button ![Script](../img/EditorManual/icons/AssetType_Script.png){: .image-inline-text .image-background } above the scene. Name it `MovingPlatform`. In
Server

2022-01-19 19:57 UTC, DoubleA-MG commented
I tried to delete and re-add the two images with "PNG" extensions but I think the names were cached or something because it didn't even show that a change occurred when making a commit. I'll let you do your magic Stanzilla.

2022-01-19 20:17 UTC, PopThosePringles commented
Yeah, images and videos get cached, I've tried finding a solution for myself but everything I have tried doesn't work. Good thing is, they do change, just doesn't update when serving locally.

2022-01-19 20:28 UTC, PopThosePringles requested changes

2022-01-19 20:28 UTC, PopThosePringles commented on src/tutorials/obby_tutorial.md
> +!!! tip "Use the ++shift+equal++ shortcut to spawn the player in Preview Mode where the scene camera location."
"where the scene camera location." -> "where the scene camera location current is".

2022-01-19 20:31 UTC, StanzillaManticore commented
> I tried to delete and re-add the two images with "PNG" extensions but I think the names were cached or something because it didn't even show that a change occurred when making a commit. I'll let you do your magic Stanzilla.

That's just Windows not letting you do it easily because case insensitivity, I'll do it.

2022-01-19 21:40 UTC, PopThosePringles approved these changes

2022-01-24 09:37 UTC, merged