Add Data Tables Reference
ManticoreGamesInc/platform-documentation pull request #945
Opened 2022-02-07 15:45 UTC by PopThosePringles

2022-02-07 23:35 UTC, DoubleA-MG requested changes
Feel like there might be need for a final h2 (Learn More or Use Cases)

2022-02-07 23:35 UTC, DoubleA-MG commented on src/references/data_tables.md
> +## Overview
Overview is blank? Probably meant to be up on line 10

2022-02-07 23:35 UTC, DoubleA-MG commented on src/references/data_tables.md
> +Creators can modify the column type by clicking on the warning icon in the column header. The **Column Settings** window will pop up allowing creators to modify the type and the column name. All colu
Perhaps a warning that the type of a row cannot be changed easily.

2022-02-07 23:35 UTC, DoubleA-MG commented on src/references/data_tables.md
> +A **Data Table** is a text file called a `csv` (Command-separated Values). This allow creators to easily modify the data of a data table. So adding large amounts of data would be easier by editing th
Comma-Separated Values

2022-02-08 10:01 UTC, CommanderFoo commented on src/references/data_tables.md
> +Creators can modify the column type by clicking on the warning icon in the column header. The **Column Settings** window will pop up allowing creators to modify the type and the column name. All colu
I did have this in, but removed it, as it was changed. But looks to be removed again. Not sure why.

2022-02-08 17:27 UTC, DoubleA-MG approved these changes

2022-02-08 21:39 UTC, merged